### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by Nitingadhiya** [SidaHoil/force_update#1]
When I'm testing on Android Device. yet I can't check on iOS device.
No implementation found for method openappstore on channel flutter.moum.open_appstore

E/flutter ( 9888): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 9888): <asynchronous suspension>
E/flutter ( 9888): #1      OpenAppstore.launch (package:forceupdate/forceupdate.dart:186:5)
E/flutter ( 9888): <asynchronous suspension>
E/flutter ( 9888):

**Comment by amitsh223** [comment]
same thing happend with me.
any correction @Nitingadhiya

**Comment by Nitingadhiya** [comment]
Not yet. But I'm using with API and check version code. If Application version is below the current version then will open manually popup Window. @amitsh223 

Let me know If you need further help.

**Comment by amitsh223** [comment]
yup i have done the same @Nitingadhiya
